-- MySQL Script generated by MySQL Workbench
-- Thu Feb 13 23:40:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_barbearia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_barbearia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_barbearia` DEFAULT CHARACTER SET utf8 ;
USE `db_barbearia` ;

-- -----------------------------------------------------
-- Table `db_barbearia`.`contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_barbearia`.`contactos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_barbearia`.`localizacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_barbearia`.`localizacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `provincia` VARCHAR(100) NULL,
  `bairro` VARCHAR(100) NULL,
  `rua` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_barbearia`.`barbearias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_barbearia`.`barbearias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `descricao` TEXT NULL,
  `imagem` VARCHAR(100) NULL,
  `contactos_id` INT NOT NULL,
  `localizacoes_id` INT NOT NULL,
  `senha` VARCHAR(250) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_barbearias_contactos_idx` (`contactos_id` ASC) VISIBLE,
  INDEX `fk_barbearias_localizacoes1_idx` (`localizacoes_id` ASC) VISIBLE,
  CONSTRAINT `fk_barbearias_contactos`
    FOREIGN KEY (`contactos_id`)
    REFERENCES `db_barbearia`.`contactos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_barbearias_localizacoes1`
    FOREIGN KEY (`localizacoes_id`)
    REFERENCES `db_barbearia`.`localizacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_barbearia`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_barbearia`.`servicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_barbearia`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_barbearia`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(250) NOT NULL,
  `contactos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clientes_contactos1_idx` (`contactos_id` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_contactos1`
    FOREIGN KEY (`contactos_id`)
    REFERENCES `db_barbearia`.`contactos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_barbearia`.`macacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_barbearia`.`macacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(100) NULL DEFAULT 'Confirmado',
  `data` TIMESTAMP NULL,
  `barbearias_id` INT NOT NULL,
  `clientes_id` INT NOT NULL,
  `servicos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_macacoes_barbearias1_idx` (`barbearias_id` ASC) VISIBLE,
  INDEX `fk_macacoes_clientes1_idx` (`clientes_id` ASC) VISIBLE,
  INDEX `fk_macacoes_servicos1_idx` (`servicos_id` ASC) VISIBLE,
  CONSTRAINT `fk_macacoes_barbearias1`
    FOREIGN KEY (`barbearias_id`)
    REFERENCES `db_barbearia`.`barbearias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_macacoes_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `db_barbearia`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_macacoes_servicos1`
    FOREIGN KEY (`servicos_id`)
    REFERENCES `db_barbearia`.`servicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
